# Generated by Django 5.1 on 2025-07-22 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('requirements', models.TextField(verbose_name='Prérequis')),
                ('contract_type', models.CharField(choices=[('CDI', 'Contrat à durée indéterminée'), ('CDD', 'Contrat à durée déterminée'), ('STAGE', 'Stage'), ('ALTERNANCE', 'Alternance'), ('FREELANCE', 'Freelance'), ('INTERIM', 'Intérim')], max_length=20, verbose_name='Type de contrat')),
                ('experience_level', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('JUNIOR', 'Junior (1-3 ans)'), ('SENIOR', 'Senior (3-5 ans)'), ('EXPERT', 'Expert (5+ ans)')], max_length=20, verbose_name="Niveau d'expérience")),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire minimum')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire maximum')),
                ('location', models.CharField(max_length=200, verbose_name='Localisation')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Télétravail possible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_filled', models.BooleanField(default=False, verbose_name='Poste pourvu')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company', verbose_name='Entreprise')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='Lettre de motivation')),
                ('resume', models.FileField(upload_to='applications/resumes/', verbose_name='CV')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('REVIEWED', "En cours d'examen"), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée'), ('WITHDRAWN', 'Retirée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Candidature déposée le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Examinée le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Examinée par')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name="Offre d'emploi")),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
