services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: france_chomage
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django -d france_chomage"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Application Django
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://django:django123@db:5432/france_chomage
    volumes:
      - .:/app

volumes:
  postgres_data:
