# Generated by Django 5.1 on 2025-07-22 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('APPLICATIONS', 'Candidatures'), ('JOBS', "Offres d'emploi"), ('COMPANIES', 'Entreprises')], max_length=20, verbose_name="Type d'export")),
                ('file_path', models.CharField(max_length=500, verbose_name='Chemin du fichier')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('record_count', models.IntegerField(verbose_name="Nombre d'enregistrements")),
                ('exported_at', models.DateTimeField(auto_now_add=True, verbose_name='Exporté le')),
                ('filters_applied', models.JSONField(blank=True, default=dict, verbose_name='Filtres appliqués')),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Exporté par')),
            ],
            options={
                'verbose_name': 'Export CSV',
                'verbose_name_plural': 'Exports CSV',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='CSVImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('APPLICATIONS', 'Candidatures'), ('JOBS', "Offres d'emploi"), ('COMPANIES', 'Entreprises')], max_length=20, verbose_name="Type d'import")),
                ('file_path', models.CharField(max_length=500, verbose_name='Chemin du fichier')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('records_processed', models.IntegerField(default=0, verbose_name='Enregistrements traités')),
                ('records_created', models.IntegerField(default=0, verbose_name='Enregistrements créés')),
                ('records_updated', models.IntegerField(default=0, verbose_name='Enregistrements mis à jour')),
                ('records_failed', models.IntegerField(default=0, verbose_name='Enregistrements échoués')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importé le')),
                ('error_log', models.TextField(blank=True, verbose_name="Log d'erreurs")),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Importé par')),
            ],
            options={
                'verbose_name': 'Import CSV',
                'verbose_name_plural': 'Imports CSV',
                'ordering': ['-imported_at'],
            },
        ),
    ]
