# Generated by Django 4.2.23 on 2025-07-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvimport',
            name='imported_by',
        ),
        migrations.DeleteModel(
            name='CSVExport',
        ),
        migrations.DeleteModel(
            name='CSVImport',
        ),
    ]
