# Generated by Django 5.1 on 2025-07-23 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employer',
            field=models.ForeignKey(blank=True, help_text="L'employeur responsable de cette entreprise", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies_managed', to=settings.AUTH_USER_MODEL, verbose_name='Employeur responsable'),
        ),
    ]
