# Generated by Django 5.1 on 2025-07-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo officiel de l'entreprise (format: JPG, PNG, GIF, max 2MB)", null=True, upload_to='companies/logos/', verbose_name="Logo de l'entreprise"),
        ),
    ]
