# Generated by Django 4.2.23 on 2025-07-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo officiel de l'entreprise (format: JPG, PNG, GIF, WebP, max 2MB)", null=True, upload_to='companies/logos/', verbose_name="Logo de l'entreprise"),
        ),
    ]
